/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./erc20.sol";
export type { erc20Sol };
import type * as stablecoinSol from "./stablecoin.sol";
export type { stablecoinSol };
export type { AggregatorV3Interface } from "./AggregatorV3Interface";
