/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20Sol from "./erc20.sol";
export * as stablecoinSol from "./stablecoin.sol";
export { AggregatorV3Interface__factory } from "./AggregatorV3Interface__factory";
